### ISSUE TITLE
Ways to implement extenstions

### ISSUE THREAD

**Issue by danPixl** [racklab/labHTTP#9]

**Comment by leo60228** [comment]
API Proposal: https://gist.github.com/leo60228/8be2208e82531e59c36a7a9301b94088

**Comment by danPixl** [comment]
My proposal: https://gist.github.com/danPixl/6bb2e0617e4e276c71bffef3404906ee

**Comment by leo60228** [comment]
I tried to make the extensions versatile, and there are several things I can't figure out how to implement using that, including request routers and 404 handlers. Some things would also have relatively bad performance, like a blogging engine.

EDIT: I tried to make it so that all non-essential features of Monorail could be implemented as extensions.

**Comment by danPixl** [comment]
Yeah. Your approach is definitely much more powerful and a bit faster in some cases, but I think one of the advantages of mine is that it already ties into the style that Monorail was done in. (using the `%variable%` system). A giant problem with mine is trying to figure out which order to run the extensions in. I'd like to avoid databases where possible, and follow the UNIX philosophy (everything should be a filesystem).

Also, I'd like the error handling done by Monorail itself.

**Comment by leo60228** [comment]
This could be worked around via some helpers: http://bit.ly/2myzhx0

EDIT: Typo fixed, use the new URL

**Comment by danPixl** [comment]
We've now reached the end of Pivot Milestone 1, thanks to @leo60228's hard work!
